/**:
  ros__parameters:
    direction:
      x:  0.0
      y:  0.0
      z:  1.0
    length: 0.05
    offset: 0.0
    pitch:  0.01
    no_push_back: true
    horizontal_multiplier: 32
    proportional_augmentation: true
    horizontal_angular_pitch: 0.0031416
    vertical_angular_pitch: 0.0349
    center:
      x:  1.255
      y: -0.14
      z:  0.23

